@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.signJwt}}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"teste@mail.com",
    "password":"11111111"
}

### Get user by id
# @name findUserById
GET {{baseUrl}}/user/1
Authorization: Bearer {{jwtToken}}

### create a user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name":"Teste",
    "email":"teste@mail.com",
    "password":"11111111"
}

### update a user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name":"Mariane",
    "email":"mari@mail.com"

}

### update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "currentPassword":"11111111",
    "newPassword":"123456"

}

### get logged user
# @name getLoggedUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### delete logged user
# @name deleteLoggedUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}