@baseUrl = http://localhost:3000

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"user@mail.com",
    "password":"11111111"
}

### Get user by id
# @name findUserById
GET {{baseUrl}}/user/aaaaa
